# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Delete Package

on:
  workflow_dispatch:

jobs:
  delete:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Delete Release
      uses: WyriHaximus/github-action-delete-package@master
      if: steps.get-revision-number.outputs.info != ''
      with:
        packageVersionId: 5.0.6
      env:
        GITHUB_TOKEN: ${{ github.token }}
