# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Delete Package

on:
  workflow_dispatch:

jobs:
  delete:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Get version id
      uses: castlabs/get-package-version-id-action@v2.0
      id: versions
      with:
        version: '5.0.6'
    - name: Delete Release
      uses: actions/delete-package-versions@v4
      if: ${{ steps.versions.outputs.ids != '' }}
      with: 
        package-type: 'maven'
        package-version-ids: '${{ steps.versions.outputs.ids }}'
        token: ${{ github.token }}
      continue-on-error: true
    
