# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Delete Package

on:
  workflow_dispatch:

jobs:
  delete:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Delete Release
      uses: actions/delete-package-versions@v4
      with: 
        package-name: 'de.fraunhofer.iais.eis.ids.open-broker-common'
        package-type: 'maven'
        ignore-versions: '5.0.4, 5.0.3'
        token: ${{ github.token }}
      continue-on-error: true
    - name: Delete Release
      uses: actions/delete-package-versions@v4
      with: 
        package-name: 'de.fraunhofer.iais.eis.ids.open-index-common'
        package-type: 'maven'
        ignore-versions: '5.0.4'
        token: ${{ github.token }}
    - name: Delete Release
      uses: actions/delete-package-versions@v4
      with: 
        package-name: 'de.fraunhofer.iais.eis.ids.broker-open-core'
        package-type: 'maven'
        ignore-versions: '5.0.4'
        token: ${{ github.token }}
    - name: Delete Release
      uses: actions/delete-package-versions@v4
      with: 
        package-name: 'de.fraunhofer.iais.eis.ids.broker-core'
        package-type: 'maven'
        ignore-versions: '5.0.4'
        token: ${{ github.token }}
    #  uses: WyriHaximus/github-action-delete-package@master
    #  if: steps.get-revision-number.outputs.info != ''
    #  with:
    #    packageVersionId: 5.0.6
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}
