# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Get revision number from pom.xml
      id: get-revision-number
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'pom.xml'
        xpath: '//*[local-name()="revision"]'
      
    - run: echo "The revision number is ${{ steps.get-revision-number.outputs.info }}"
    
    - name: Build with Maven
#     run: mvn -B package --file pom.xml
      run: |
        mvn clean package -U -Drevision=${{ steps.get-revision-number.outputs.info }}
        mkdir staging && cp /home/runner/work/metadata-broker-open-core/metadata-broker-open-core/broker-core/target/*.jar staging
#     - run: mvn --batch-mode --update-snapshots verify

    - name: Set up a cache for Maven
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: metadata-broker-open-core_${{ steps.get-revision-number.outputs.info }}
        path: staging
        
#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
        

