# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Get revision number from pom.xml
      id: get-revision-number
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'pom.xml'
        xpath: '//*[local-name()="revision"]'
        
    - name: Setup Maven
      uses: s4u/maven-settings-action@v2.3.0
      with:
        servers: |
          [{
            "id": "github-IDS-Components",
            "username": "${{ secrets.USER_PACKAGE_READ }}",
            "password": "${{ secrets.TOKEN_PACKAGE_READ }}"
          }]
          
    - name: Build with Maven
      run: mvn clean package -U -Drevision=${{ steps.get-revision-number.outputs.info }}

    - name: Set up a cache for Maven
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: metadata-broker-open-core_open-index-common_${{ steps.get-revision-number.outputs.info }}
        path: ${{ github.workspace }}/open-index-common/target
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: metadata-broker-open-core_open-broker-common_${{ steps.get-revision-number.outputs.info }}
        path: ${{ github.workspace }}/open-broker-common/target
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: metadata-broker-open-core_broker-core_${{ steps.get-revision-number.outputs.info }}
        path: ${{ github.workspace }}/broker-core/target
        
    #- name: Delete Release
    #  uses: WyriHaximus/github-action-delete-package@master
    #  if: steps.get-revision-number.outputs.info != ''
    #  with:
    #    packageVersionId: ${{ steps.get-revision-number.outputs.info }}
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}
    - name: Setup Maven
      uses: s4u/maven-settings-action@v2.3.0
      with:
        servers: |
          [{
            "id": "github-IDS-Components",
            "username": "${{ secrets.USER_PACKAGE_READ }}",
            "password": "${{ secrets.TOKEN_PACKAGE_READ }}"
          }]
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -Drevision=${{ steps.get-revision-number.outputs.info }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
